import { defineType } from 'sanity'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'Page: About & Curriculum Dossier',
  type: 'document',
  groups: [
    { name: 'profile', title: '👤 Scholar Profile & Bio', default: true },
    { name: 'metrics', title: '📊 Bibliometrics' },
    { name: 'pillars', title: '🏛️ Theoretical Pillars' },
    { name: 'timeline', title: '⏱️ Timeline & Skills' },
    { name: 'seo', title: '🔍 SEO & Meta' },
  ],
  fields: [
    {
      name: 'kicker',
      title: 'Top Monospace Kicker',
      type: 'string',
      group: 'profile',
      description: '📍 Where it appears: Top telemetry tag on /about (e.g. CURRICULUM VITAE & SCHOLARLY DOSSIER).',
      placeholder: 'CURRICULUM VITAE & SCHOLARLY DOSSIER // DEPT. OF COGNITIVE COMPUTATION',
      initialValue: 'CURRICULUM VITAE & SCHOLARLY DOSSIER // DEPT. OF COGNITIVE COMPUTATION',
    },
    {
      name: 'title',
      title: 'Page Title',
      type: 'string',
      group: 'profile',
      description: '📍 Where it appears: The main H1 title on the /about page.',
      placeholder: 'Curriculum & Editorial Dossier',
      initialValue: 'Curriculum & Editorial Dossier',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'profileImage',
      title: 'Profile Portrait Image',
      type: 'image',
      group: 'profile',
      description: '📍 Where it appears: Square portrait photo in the left scholar profile card.',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alt Text',
          placeholder: 'Sudip Jana portrait photo',
        },
      ],
    },
    {
      name: 'headline',
      title: 'Epistemic Thesis Headline',
      type: 'text',
      rows: 3,
      group: 'profile',
      description: '📍 Where it appears: Large serif quote and subtitle under the page title.',
      placeholder: 'Investigating the mathematical continuum between non-equilibrium statistical mechanics, morphogenetic substrates, and synthetic cognitive architectures.',
      initialValue:
        'Investigating the mathematical continuum between non-equilibrium statistical mechanics, morphogenetic substrates, and synthetic cognitive architectures.',
    },
    {
      name: 'abstract',
      title: 'Scholarly Abstract / Bio Narrative',
      type: 'text',
      rows: 4,
      group: 'profile',
      description: '📍 Where it appears: The second paragraph under the Epistemic Thesis on /about.',
      placeholder: 'Our laboratory focuses on the fundamental question: How do self-organizing physical substrates spontaneously compute, minimize informational entropy, and manifest cognitive invariants?',
      initialValue:
        'Our laboratory focuses on the fundamental question: How do self-organizing physical substrates spontaneously compute, minimize informational entropy, and manifest cognitive invariants? By unifying Turing reaction-diffusion dynamics, Friston variational mechanics, and differential geometric latent representations, Synthese operates as both a formal theoretical press and an executable experimental sandbox.',
    },
    {
      name: 'bioStory',
      title: 'Full Extended Biography (Portable Text)',
      type: 'blockContent',
      group: 'profile',
      description: 'Optional rich-text story blocks for long-form biographies.',
    },
    {
      name: 'orcid',
      title: 'ORCID Identifier',
      type: 'string',
      group: 'profile',
      description: '📍 Where it appears: Clickable ORCID badge in the profile card.',
      placeholder: '0000-0002-1825-0097',
      initialValue: '0000-0002-1825-0097',
    },
    {
      name: 'pgpKey',
      title: 'PGP Public Key',
      type: 'string',
      group: 'profile',
      description: '📍 Where it appears: Clickable PGP fingerprint badge in the header action bar.',
      placeholder: '0x8F3C9A1E 4D27 B901',
      initialValue: '0x8F3C9A1E 4D27 B901',
    },
    {
      name: 'metrics',
      title: 'Bibliometric Highlights',
      type: 'object',
      group: 'metrics',
      description: '📍 Where it appears: The 4 metric boxes (Citations, h-Index, Manuscripts, Models) in the profile card.',
      fields: [
        { name: 'citations', type: 'string', title: 'Citations', placeholder: '1,480+', initialValue: '1,480+' },
        { name: 'hIndex', type: 'string', title: 'h-Index', placeholder: '18', initialValue: '18' },
        { name: 'publications', type: 'string', title: 'Manuscripts', placeholder: '24', initialValue: '24' },
        { name: 'activeSimulations', type: 'string', title: 'Active Models', placeholder: '14', initialValue: '14' },
      ],
    },
    {
      name: 'epistemicPillars',
      title: 'Core Theoretical Pillars',
      type: 'array',
      group: 'pillars',
      description: '📍 Where it appears: 3 cards showing your primary research pillars on /about.',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'title', type: 'string', title: 'Pillar Title', placeholder: 'Thermodynamic Morphogenesis' },
            { name: 'discipline', type: 'string', title: 'Discipline / Field', placeholder: 'Nonlinear PDEs & Physical Substrates' },
            { name: 'summary', type: 'text', rows: 2, title: 'Summary', placeholder: 'Continuous reaction-diffusion Turing substrates functioning as asynchronous logic networks.' },
          ],
        },
      ],
      initialValue: [
        {
          title: 'Thermodynamic Morphogenesis',
          discipline: 'Nonlinear PDEs & Physical Substrates',
          summary:
            'Continuous reaction-diffusion Turing substrates functioning as asynchronous, ultra-low-power logic networks that bypass von Neumann architectural constraints.',
        },
        {
          title: 'Geometric Deep Learning & Manifolds',
          discipline: 'Differential Geometry & Information Theory',
          summary:
            'Analyzing neural representation spaces through persistent homology and hyperbolic embeddings to prevent semantic drift and characterize latent manifold curvature.',
        },
        {
          title: 'Variational Neurodynamics',
          discipline: 'Free Energy Principle & Bayesian Mechanics',
          summary:
            'Formulating normative bounds on cortical active inference where Markov blankets delineate internal informational states from external thermodynamic surprise.',
        },
      ],
    },
    {
      name: 'skillsHeadline',
      title: 'Skills Section Title',
      type: 'string',
      group: 'timeline',
      placeholder: 'Core Competencies & Tooling',
      initialValue: 'Core Competencies & Tooling',
    },
    {
      name: 'skills',
      title: 'Skills / Tech Tags',
      type: 'array',
      group: 'timeline',
      description: 'Tag badges displayed under the research pillars.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    },
    {
      name: 'showTimeline',
      title: 'Show Experience / Career Timeline',
      type: 'boolean',
      group: 'timeline',
      description: 'Toggle on to show the chronological career timeline on /about.',
      initialValue: true,
    },
    {
      name: 'timelineHeading',
      title: 'Timeline Section Heading',
      type: 'string',
      group: 'timeline',
      placeholder: 'Curriculum Temporale & Appointments',
      initialValue: 'Curriculum Temporale & Appointments',
    },
    {
      name: 'resumeUrl',
      title: 'External Resume / PDF CV URL (Optional)',
      type: 'string',
      group: 'timeline',
      description: 'Optional link to a hosted PDF CV. If blank, clicking download generates an instant markdown dossier.',
      placeholder: 'https://example.com/cv.pdf',
    },
    {
      name: 'seo',
      title: 'About Page SEO',
      type: 'seo',
      group: 'seo',
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'headline',
      media: 'profileImage',
    },
  },
})
